---

- ansible.builtin.get_url:
    url: "{{ erlang_debian_key }}"
    dest: "{{ erlang_debian_keyring }}"
  become: yes

- ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ erlang_debian_keyring }}] {{ erlang_debian_repo }} {{ erlang_debian_dist }} contrib"
    update_cache: false
    state: present
  become: yes

- name: install packages
  ansible.builtin.apt:
    name: "{{ erlang_debian_packages | join(',') }}"
    update_cache: yes
  become: yes
