---

- apt_key:
    url: "{{ erlang_apt_key }}"
    state: present
  become: yes

- apt_repository:
    repo: "{{ erlang_repo }}"
    state: present
  become: yes

- name: install packages
  apt:
    name: "{{ erlang_packages | join(',') }}"
    update_cache: yes
  become: yes
