---

- name: "{{ ansible_system }} vars"
  include_vars: "{{ ansible_system|lower }}.yml"

- name: download rustup-init
  ansible.builtin.get_url:
    url: "https://static.rust-lang.org/rustup/dist/{{ ansible_architecture }}-{{ rust_ostype }}/rustup-init"
    dest: /tmp
    mode: '0755'

- name: install rustup
  ansible.builtin.command: /tmp/rustup-init -y --no-modify-path

- name: remove rustup-init
  ansible.builtin.file:
    path: /tmp/rustup-init
    state: absent

- name: download rust-analyzer
  ansible.builtin.get_url:
    url: "https://github.com/rust-analyzer/rust-analyzer/releases/{{ rust_analyzer_version }}/download/rust-analyzer-{{ ansible_architecture }}-{{ rust_ostype }}.gz"
    dest: /usr/local/bin/rust-analyzer.gz
    mode: '0755'
  become: yes

- name: install rust-analyzer
  ansible.builtin.command: gunzip --force /usr/local/bin/rust-analyzer.gz
  become: yes

- name: remove rust-analyzer download
  ansible.builtin.file:
    path: /usr/local/bin/rust-analyzer.gz
    state: absent
