---
- hosts: localhost
  vars:
    user: "{{ ansible_user_id }}"
    dotfiles_path: dotfiles
    dotfiles_branch: linux
    wm: i3
  roles:
    - base
    - dotfiles
    - ruby
    - rust
    - terraform
    - heroku
    - wm
