---
- name: Update workstations
  hosts: workstations
  roles:
    - base
    - neovim
    - wezterm
    - dotfiles
    - docker
    - ruby
    - rust
    - nodejs
    - terraform
    - heroku
    - pack
    - wm
