---

- name: clone dotfiles
  git:
    repo: https://github.com/eoconnell/dotfiles.git
    dest: "/home/{{ user }}/{{ dotfiles_path }}"
    version: " {{ dotfiles_branch }}"
  become: yes
  become_user: "{{ user }}"

- name: link bin
  make:
    chdir: "/home/{{ user }}/{{ dotfiles_path }}"
    target: bin

- name: link dotfiles
  make:
    chdir: "/home/{{ user }}/{{ dotfiles_path }}"
    target: dotfiles
