---

- name: clone dotfiles
  git:
    repo: https://github.com/eoconnell/dotfiles.git
    dest: "/home/{{ user }}/{{ dotfiles_path }}"
    version: " {{ dotfiles_branch }}"
    update: no
  become: yes
  become_user: "{{ user }}"

- name: install dotfiles
  make:
    chdir: "/home/{{ user }}/{{ dotfiles_path }}"
    target: install
