---

- name: clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/eoconnell/dotfiles.git
    dest: "/home/{{ user }}/{{ dotfiles_path }}"
    version: " {{ dotfiles_branch }}"
    update: no

- name: install dotfiles
  ansible.builtin.make:
    chdir: "/home/{{ user }}/{{ dotfiles_path }}"
    target: install
