---
- name: install packages
  apt:
    name: "{{ nodejs_packages | join(',') }}"
    update_cache: yes
  become: yes

- name: download nvm install
  get_url:
    url: "https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh"
    dest: /tmp/nvm-install.sh
    mode: '0755'

- name: install nvm
  command: /tmp/nvm-install.sh

- name: remove nvm install script
  file:
    path: /tmp/nvm-install.sh
    state: absent
