---
- name: install packages
  ansible.builtin.apt:
    name: "{{ nodejs_debian_packages | join(',') }}"
    update_cache: yes
  become: yes

- name: download nvm install
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh"
    dest: /tmp/nvm-install.sh
    mode: '0755'

- name: install nvm
  ansible.builtin.command: /tmp/nvm-install.sh

- name: remove nvm install script
  ansible.builtin.file:
    path: /tmp/nvm-install.sh
    state: absent
