---

  # 2026-02-28 wezterm_debian_repo is unavailable
- ansible.builtin.deb822_repository:
    name: wezterm
    types: deb
    uris: "{{ wezterm_debian_repo }}"
    suites: "*"
    components: "*"
    signed_by: "{{ wezterm_debian_gpg_key }}"
    state: present
    enabled: true
  become: yes

- name: install packages
  ansible.builtin.apt:
    name: "{{ wezterm_debian_packages | join(',') }}"
    update_cache: yes
  become: yes
