---

- apt_key:
    url: "{{ terraform_gpg_key }}"
    state: present
  become: yes

- apt_repository:
    repo: "deb [arch=amd64] {{ terraform_repo }} bullseye main"
    state: present
  become: yes

- name: install packages
  apt:
    name: "{{ terraform_packages | join(',') }}"
    update_cache: yes
  become: yes
