---

- ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "{{ terraform_debian_repo }}"
    suites: "{{ terraform_debian_dist }}"
    components: main
    signed_by: "{{ terraform_debian_gpg_key }}"
    state: present
    enabled: true
  become: yes

- name: install packages
  ansible.builtin.apt:
    name: "{{ terraform_debian_packages | join(',') }}"
    update_cache: yes
  become: yes
