debian_packages:
  - bash-completion
  - ca-certificates
  - curl
  - diffstat
  - dnsutils
  - gcc
  - git
  - gnupg2
  - grep
  - gzip
  - hostname
  - iptables
  - less
  - lsof
  - make
  - mount
  - net-tools
  - rxvt-unicode
  - software-properties-common
  - ssh
  - strace
  - sudo
  - tar
  - tmux
  - tree
  - unzip
  - vim
  - xclip
  - xcompmgr
  - zip
  - zsh
