---

- ansible.builtin.deb822_repository:
    name: heroku
    types: deb
    uris: "{{ heroku_debian_repo }}"
    signed_by: "{{ heroku_debian_key }}"
    suites: ./
    state: present
    enabled: true
  become: yes


- name: install packages
  ansible.builtin.apt:
    name: "{{ heroku_debian_packages | join(',') }}"
    update_cache: yes
  become: yes
