---

- ansible.builtin.apt:
    name: apt-transport-https
  become: yes

- ansible.builtin.apt_key:
    url: "{{ heroku_debian_key }}"
    keyring: "{{ heroku_debian_keyring }}"
    state: present
  become: yes

- ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ heroku_debian_keyring }}] {{ heroku_debian_repo }} ./"
    update_cache: false
    state: present
  become: yes

- name: install packages
  ansible.builtin.apt:
    name: "{{ heroku_debian_packages | join(',') }}"
    update_cache: yes
  become: yes
