---

- apt:
    name: apt-transport-https
  become: yes

- apt_key:
    url: "{{ heroku_apt_key }}"
    state: present
  become: yes

- apt_repository:
    repo: "deb {{ heroku_repo }} ./"
    state: present
  become: yes

- name: install packages
  apt:
    name: "{{ heroku_packages | join(',') }}"
    update_cache: yes
  become: yes
