---

- ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "{{ docker_debian_repo }}"
    suites: "{{ docker_debian_dist }}"
    components: stable
    signed_by: "{{ docker_debian_gpg_key }}"
    state: present
    enabled: true
  become: yes

- name: install packages
  ansible.builtin.apt:
    name: "{{ docker_debian_packages | join(',') }}"
    update_cache: yes
  become: yes

- name: create docker group
  ansible.builtin.group:
    name: docker
    state: present
