---

- name: disable apt translations
  lineinfile:
    path: /etc/apt/apt.conf.d/99translations
    line: Acquire::Languages "none";
  become: yes

- name: update apt
  apt:
    update_cache: yes
  become: yes

- name: install packages
  apt:
    name: "{{ debian_packages | join(',') }}"
  become: yes

- name: remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: yes

- name: remove useless packages from the cache
  apt:
    autoclean: yes
  become: yes
