---

- name: "{{ ansible_os_family }} vars"
  include_vars: "{{ ansible_os_family|lower }}.yml"

- name: "{{ ansible_os_family }} tasks"
  include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: install scripts
  include_tasks: scripts.yml
